### ISSUE TITLE
What is reduction cell stands for?

### ISSUE THREAD

**Issue by Yuzz1020** [renqianluo/NAO#1]
Awesome idea and awesome implementation! However I have a question here, what does reduction cell stands for? For a CNN architecture, according to my understanding, only convolutional cell should be enough?

**Comment by renqianluo** [comment]
@noNameForMe1994 Hi. The reduction cell is used to reduce the spatial dimension of the feature maps which is a common practice in modern deep CNN design (ResNet, DenseNet...). And the reduction cell itself is following the design from NAS, NASNet, AmoebaNet...

**Comment by Yuzz1020** [comment]
> @noNameForMe1994 Hi. The reduction cell is used to reduce the spatial dimension of the feature maps which is a common practice in modern deep CNN design (ResNet, DenseNet...). And the reduction cell itself is following the design from NAS, NASNet, AmoebaNet...

Thx!
