### ISSUE TITLE
Confusion about computing the gradient of predictor?

### ISSUE THREAD

**Issue by wenerhg** [renqianluo/NAO#12]
In 'NAO/cnn/encoder/encoder.py', the gradient of predictor is computed as follow:
`new_arch_outputs = self.encoder_outputs - self.params['predict_lambda'] * grads_on_outputs`

However, I think the gradient should be computed as described in paper:
<a href="https://www.codecogs.com/eqnedit.php?latex=h_{t}^{'}&space;=&space;h_{t}&space;&plus;&space;\eta&space;\frac{\partial&space;f}{\partial&space;h_{t}},&space;e_{x^{'}}=\{h_{1}^{'},\dots,h_{T}^{'}\}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?h_{t}^{'}&space;=&space;h_{t}&space;&plus;&space;\eta&space;\frac{\partial&space;f}{\partial&space;h_{t}},&space;e_{x^{'}}=\{h_{1}^{'},\dots,h_{T}^{'}\}" title="h_{t}^{'} = h_{t} + \eta \frac{\partial f}{\partial h_{t}}, e_{x^{'}}=\{h_{1}^{'},\dots,h_{T}^{'}\}" /></a>

Is there an error with computing the gradient of predictor in code?

**Comment by renqianluo** [comment]
@wenerhg In the paper, for the general purpose, we denote f as the performance which is the larger the better, so we move towards the positive direction of the gradient, which shows as '+'. In the code, we use error rate as f which is the lower the better, so we need to move towards the negative direction, which shows as '-'.

**Comment by renqianluo** [comment]
@wenerhg in other words, if you use accuracy as f in code, you should move towards the positive direction and use '+'
