### ISSUE TITLE
Training final does not work

### ISSUE THREAD

**Issue by Wronskia** [renqianluo/NAO#2]
Hello,

Thank you for open-sourcing the code. The training_final does not work for NAO-WS/rnn/train_final.sh. It seems like there are few bugs.

Thanks

**Comment by renqianluo** [comment]
@Wronskia Sorry for the bugs. Have fixed those now.

**Comment by Wronskia** [comment]
@renqianluo Thank you for your quick response.

I still get this :  Should the args be replaced by args.bptt?

Traceback (most recent call last):
  File "train.py", line 303, in <module>
    val_loss = evaluate(val_data, eval_batch_size)
  File "train.py", line 159, in evaluate
    data, targets = get_batch(data_source, i, args, evaluation=True)
  File "/home/NAO-WS/rnn/utils.py", line 61, in get_batch
    seq_len = min(seq_len if seq_len else bptt, len(source) - 1 - i)
TypeError: unorderable types: int() < Namespace()


Thanks again

**Comment by renqianluo** [comment]
@Wronskia Sure. Have had a quick fix on that.
