### ISSUE TITLE
Is parameter N in train_cifar10_search.sh the same as N in paper? 

### ISSUE THREAD

**Issue by Yuzz1020** [renqianluo/NAO#3]
Hey, I'm still new to this area, but it confuses me that parameter N in train_cifar10_search.sh is multiplied by 3 when generating model. However, in the paper, it seems that N is the total normal convolution cell used to construct final model. So I'm wondering if these two Ns are the same or is N in code equals 3 * N in the paper?

**Comment by renqianluo** [comment]
@noNameForMe1994 Hi, recent works on NAS commonly follow a pattern of: stem head - convolution cell * N - reduction cell - convolution cell * N - reduction cell - auxiliary head - convolution cell * N - reduction cell (please refer to NASNet, ENAS...). So you see there are totally N*3 convolution cells and 2 reduction cells. The N in the script is the same with the N in the paper (we use N=6 as a common practice).
